/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Partie2;

import Partie2.Algorithme.Chromosome;
import Partie2.Algorithme.GA;
import src.Puzzle;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import puzzle8.Configuration;
import puzzle8.Welcom_Form;

/**
 *
 * @author ABEDSSAMED
 */
public class GeneticAlgoForm extends javax.swing.JFrame {

    /**
     * Creates new form PSOFORM
     */
    public GeneticAlgoForm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        iterations.setModel(new SpinnerNumberModel(new Integer(1000), new Integer(0), null, new Integer(1)));
        size.setModel(new SpinnerNumberModel(new Integer(100), new Integer(1), null, new Integer(1)));

        param1.setModel(new SpinnerNumberModel(new Float(0.5), new Float(0), null, new Float(0.1)));
        param2.setModel(new SpinnerNumberModel(new Float(0.5), new Float(0), null, new Float(0.1)));
        state[0][0] = Integer.parseInt(txt00.getText() == "" ? "0" : txt00.getText());
        state[0][1] = Integer.parseInt(txt01.getText() == "" ? "0" : txt01.getText());
        state[0][2] = Integer.parseInt(txt02.getText() == "" ? "0" : txt02.getText());
        state[1][0] = Integer.parseInt(txt10.getText() == "" ? "0" : txt10.getText());
        state[1][1] = Integer.parseInt(txt11.getText() == "" ? "0" : txt11.getText());
        state[1][2] = Integer.parseInt(txt12.getText() == "" ? "0" : txt12.getText());
        state[2][0] = Integer.parseInt(txt20.getText() == "" ? "0" : txt20.getText());
        state[2][1] = Integer.parseInt(txt21.getText() == "" ? "0" : txt21.getText());
        state[2][2] = Integer.parseInt(txt22.getText() == "" ? "0" : txt22.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        param1 = new javax.swing.JSpinner();
        size = new javax.swing.JSpinner();
        iterations = new javax.swing.JSpinner();
        param2 = new javax.swing.JSpinner();
        btnSolv = new javax.swing.JButton();
        btnSolv1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolution = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtExplored = new javax.swing.JLabel();
        txtgen = new javax.swing.JLabel();
        txtSolSize = new javax.swing.JLabel();
        textTime = new javax.swing.JLabel();
        cbxman = new javax.swing.JCheckBox();
        txt00 = new javax.swing.JTextField();
        txt01 = new javax.swing.JTextField();
        txt02 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre max de génération :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Taille d'une génération :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Taux de croisement:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Taux de mutation:");

        btnSolv.setBackground(new java.awt.Color(102, 0, 204));
        btnSolv.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSolv.setForeground(new java.awt.Color(255, 255, 255));
        btnSolv.setText("Randomiser");
        btnSolv.setToolTipText("La résolution peut prendre long temp !!");
        btnSolv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnSolv.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSolvStateChanged(evt);
            }
        });
        btnSolv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolvMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSolvMousePressed(evt);
            }
        });
        btnSolv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolvActionPerformed(evt);
            }
        });
        btnSolv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSolvKeyPressed(evt);
            }
        });

        btnSolv1.setBackground(new java.awt.Color(102, 0, 204));
        btnSolv1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSolv1.setForeground(new java.awt.Color(255, 255, 255));
        btnSolv1.setText("Résoudre");
        btnSolv1.setToolTipText("La résolution peut prendre long temp !!");
        btnSolv1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnSolv1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSolv1StateChanged(evt);
            }
        });
        btnSolv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolv1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSolv1MousePressed(evt);
            }
        });
        btnSolv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolv1ActionPerformed(evt);
            }
        });
        btnSolv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSolv1KeyPressed(evt);
            }
        });

        txtSolution.setEditable(false);
        txtSolution.setBackground(new java.awt.Color(255, 255, 255));
        txtSolution.setColumns(20);
        txtSolution.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtSolution.setForeground(new java.awt.Color(0, 0, 0));
        txtSolution.setRows(5);
        txtSolution.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204)));
        jScrollPane2.setViewportView(txtSolution);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Algorithme Génétique");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Solution :");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Taille  de la Solution :");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre de génération :");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Temps d'exécution :");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre de chromosome :");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle8/Windows_Close_Program_22531 (1).png"))); // NOI18N
        jButton3.setToolTipText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtExplored.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtExplored.setForeground(new java.awt.Color(0, 0, 0));

        txtgen.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtgen.setForeground(new java.awt.Color(0, 0, 0));

        txtSolSize.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtSolSize.setForeground(new java.awt.Color(0, 0, 0));

        textTime.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        textTime.setForeground(new java.awt.Color(0, 0, 0));

        cbxman.setBackground(new java.awt.Color(255, 255, 255));
        cbxman.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cbxman.setForeground(new java.awt.Color(0, 0, 0));
        cbxman.setText("Saisir manuale");
        cbxman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmanActionPerformed(evt);
            }
        });

        txt00.setBackground(new java.awt.Color(255, 255, 255));
        txt00.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt00.setForeground(new java.awt.Color(0, 0, 0));
        txt00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt00.setText("7");
        txt00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt00.setEnabled(false);
        txt00.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt01.setBackground(new java.awt.Color(255, 255, 255));
        txt01.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt01.setForeground(new java.awt.Color(0, 0, 0));
        txt01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt01.setText("1");
        txt01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt01.setEnabled(false);
        txt01.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt02.setBackground(new java.awt.Color(255, 255, 255));
        txt02.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt02.setForeground(new java.awt.Color(0, 0, 0));
        txt02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt02.setText("3");
        txt02.setToolTipText("");
        txt02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt02.setEnabled(false);
        txt02.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt12.setBackground(new java.awt.Color(255, 255, 255));
        txt12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt12.setForeground(new java.awt.Color(0, 0, 0));
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setText("4");
        txt12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt12.setEnabled(false);
        txt12.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt11.setBackground(new java.awt.Color(255, 255, 255));
        txt11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt11.setForeground(new java.awt.Color(0, 0, 0));
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setText("6");
        txt11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt11.setEnabled(false);
        txt11.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt10.setBackground(new java.awt.Color(255, 255, 255));
        txt10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt10.setForeground(new java.awt.Color(0, 0, 0));
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("2");
        txt10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt10.setEnabled(false);
        txt10.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt20.setBackground(new java.awt.Color(255, 255, 255));
        txt20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt20.setForeground(new java.awt.Color(0, 0, 0));
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setText("8");
        txt20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt20.setEnabled(false);
        txt20.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt21.setBackground(new java.awt.Color(255, 255, 255));
        txt21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt21.setForeground(new java.awt.Color(0, 0, 0));
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setText("0");
        txt21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt21.setEnabled(false);
        txt21.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt22.setBackground(new java.awt.Color(255, 255, 255));
        txt22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt22.setForeground(new java.awt.Color(0, 0, 0));
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setText("5");
        txt22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt22.setEnabled(false);
        txt22.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iterations, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 526, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxman, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSolSize, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtExplored, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSolv, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSolv1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSolSize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExplored, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSolv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSolv1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolvStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSolvStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvStateChanged

    private void btnSolvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolvMouseClicked
        // TODO add your handling code here:
        // txttime.setText("Entrain de resoudre ....");
    }//GEN-LAST:event_btnSolvMouseClicked

    private void btnSolvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolvMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvMousePressed

    private void btnSolvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolvActionPerformed
        // TODO add your handling code here:
        txtSolution.setText("");
        txtSolSize.setText("");
        textTime.setText("");
        txtExplored.setText("");
        txtgen.setText("");
        Cnf.generation("Medium");

        txt00.setText(Cnf.getMedium()[0][0] == 0 ? "" : Cnf.getMedium()[0][0] + "");
        txt01.setText(Cnf.getMedium()[0][1] == 0 ? "" : Cnf.getMedium()[0][1] + "");
        txt02.setText(Cnf.getMedium()[0][2] == 0 ? "" : Cnf.getMedium()[0][2] + "");
        txt10.setText(Cnf.getMedium()[1][0] == 0 ? "" : Cnf.getMedium()[1][0] + "");
        txt11.setText(Cnf.getMedium()[1][1] == 0 ? "" : Cnf.getMedium()[1][1] + "");
        txt12.setText(Cnf.getMedium()[1][2] == 0 ? "" : Cnf.getMedium()[1][2] + "");
        txt20.setText(Cnf.getMedium()[2][0] == 0 ? "" : Cnf.getMedium()[2][0] + "");
        txt21.setText(Cnf.getMedium()[2][1] == 0 ? "" : Cnf.getMedium()[2][1] + "");
        txt22.setText(Cnf.getMedium()[2][2] == 0 ? "" : Cnf.getMedium()[2][2] + "");

    }//GEN-LAST:event_btnSolvActionPerformed

    private void btnSolvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSolvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvKeyPressed

    private void btnSolv1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSolv1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolv1StateChanged

    private void btnSolv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolv1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolv1MouseClicked

    private void btnSolv1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolv1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolv1MousePressed
    static Configuration Cnf = new Configuration();

    public String str(int[][] node) {
        String str = "";
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (node[i][j] == 0) {
                    str = str + "9";
                } else {
                    str = str + node[i][j];
                }
            }

        }
        return str;
    }
    static int[][] state = new int[3][3];

    private void btnSolv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolv1ActionPerformed
        // TODO add your handling code here:
        System.out.println(txt11.getText() == "" ? "0" : txt11.getText());
        if (cbxman.isSelected()) {

            state[0][0] = Integer.parseInt(txt00.getText() == "" ? "0" : txt00.getText());
            state[0][1] = Integer.parseInt(txt01.getText() == "" ? "0" : txt01.getText());
            state[0][2] = Integer.parseInt(txt02.getText() == "" ? "0" : txt02.getText());
            state[1][0] = Integer.parseInt(txt10.getText() == "" ? "0" : txt10.getText());
            state[1][1] = Integer.parseInt(txt11.getText() == "" ? "0" : txt11.getText());
            state[1][2] = Integer.parseInt(txt12.getText() == "" ? "0" : txt12.getText());
            state[2][0] = Integer.parseInt(txt20.getText() == "" ? "0" : txt20.getText());
            state[2][1] = Integer.parseInt(txt21.getText() == "" ? "0" : txt21.getText());
            state[2][2] = Integer.parseInt(txt22.getText() == "" ? "0" : txt22.getText());

            long starttime = 0, endtime = 0;
            String solution = "";
            System.out.println("rand= " + str(Cnf.getMedium()));
            Chromosome.INITIAL_STATE = new Puzzle(Integer.parseInt(str(state)));//126893745
            GA s2 = new GA();
            try {
                size.commitEdit();
                iterations.commitEdit();
                param1.commitEdit();
                param2.commitEdit();
            } catch (java.text.ParseException e) {
            }
            s2.MAX_POP_SIZE = (Integer) size.getValue();
            s2.mut_rate = (Float) param1.getValue();
            s2.cross_rate = (Float) param2.getValue();
            starttime = System.currentTimeMillis();
            s2.initPopulation();
            solution = s2.runEvolution((Integer) iterations.getValue());
            endtime = System.currentTimeMillis();
            txtExplored.setText(s2.iterations + "");
            txtgen.setText(s2.pop_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");
            if (solution.contentEquals("X")) {
                JOptionPane.showMessageDialog(this, "Veuillez reessayer avec d'autres paramètres.", "Solution non trouvée", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtExplored.setText(s2.iterations + "");
            txtgen.setText(s2.pop_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");

            Movement_ActionP2 P = new Movement_ActionP2(solution, state);
            P.show();
        } else {
            
            long starttime = 0, endtime = 0;
            String solution = "";
            System.out.println("rand= " + str(state));
            Chromosome.INITIAL_STATE = new Puzzle(Integer.parseInt(str(Cnf.getMedium())));//126893745
            GA s2 = new GA();
            try {
                size.commitEdit();
                iterations.commitEdit();
                param1.commitEdit();
                param2.commitEdit();
            } catch (java.text.ParseException e) {
            }
            s2.MAX_POP_SIZE = (Integer) size.getValue();
            s2.mut_rate = (Float) param1.getValue();
            s2.cross_rate = (Float) param2.getValue();
            starttime = System.currentTimeMillis();
            s2.initPopulation();
            solution = s2.runEvolution((Integer) iterations.getValue());
            endtime = System.currentTimeMillis();
            txtExplored.setText(s2.iterations + "");
            txtgen.setText(s2.pop_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");
            if (solution.contentEquals("X")) {
                JOptionPane.showMessageDialog(this, "Veuillez reessayer avec d'autres paramètres.", "Solution non trouvée", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtExplored.setText(s2.iterations + "");
            txtgen.setText(s2.pop_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");

            Movement_ActionP2 P = new Movement_ActionP2(solution, Cnf.getMedium());
            P.show();
        }

    }//GEN-LAST:event_btnSolv1ActionPerformed

    private void btnSolv1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSolv1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolv1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcom_Form W = new Welcom_Form();
        W.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbxmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmanActionPerformed
        // TODO add your handling code here:
        if (cbxman.isSelected()) {
            btnSolv.setVisible(false);
            txt00.enable(true);
            txt01.enable(true);
            txt02.enable(true);
            txt10.enable(true);
            txt11.enable(true);
            txt12.enable(true);
            txt20.enable(true);
            txt21.enable(true);
            txt22.enable(true);

        } else {
            btnSolv.setVisible(true);
            txt00.enable(false);
            txt01.enable(false);
            txt02.enable(false);
            txt10.enable(false);
            txt11.enable(false);
            txt12.enable(false);
            txt20.enable(false);
            txt21.enable(false);
            txt22.enable(false);
        }
    }//GEN-LAST:event_cbxmanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneticAlgoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneticAlgoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneticAlgoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneticAlgoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneticAlgoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolv;
    private javax.swing.JButton btnSolv1;
    private javax.swing.JCheckBox cbxman;
    private javax.swing.JSpinner iterations;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner param1;
    private javax.swing.JSpinner param2;
    private javax.swing.JSpinner size;
    private javax.swing.JLabel textTime;
    private javax.swing.JTextField txt00;
    private javax.swing.JTextField txt01;
    private javax.swing.JTextField txt02;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JLabel txtExplored;
    private javax.swing.JLabel txtSolSize;
    private javax.swing.JTextArea txtSolution;
    private javax.swing.JLabel txtgen;
    // End of variables declaration//GEN-END:variables
}
