package Partie2;

import puzzle8.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABEDSSAMED
 */
public class Movement_ActionP2 extends javax.swing.JFrame {

    /**
     * Creates new form Movement_ActionP2
     */
    static int i = 0;

    static int[][] pathe = new int[3][3];
    static String path = "";
    static List<int[][]> list;

    public Movement_ActionP2(String pathG, int[][] node) {

        initComponents();
        this.path = pathG;

        pathe = node;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setDefaultCloseOperation(0);

        txt00.setText(pathe[0][0] == 0 ? "" : pathe[0][0] + "");
        txt01.setText(pathe[0][1] == 0 ? "" : pathe[0][1] + "");
        txt02.setText(pathe[0][2] == 0 ? "" : pathe[0][2] + "");
        txt10.setText(pathe[1][0] == 0 ? "" : pathe[1][0] + "");
        txt11.setText(pathe[1][1] == 0 ? "" : pathe[1][1] + "");
        txt12.setText(pathe[1][2] == 0 ? "" : pathe[1][2] + "");
        txt20.setText(pathe[2][0] == 0 ? "" : pathe[2][0] + "");
        txt21.setText(pathe[2][1] == 0 ? "" : pathe[2][1] + "");
        txt22.setText(pathe[2][2] == 0 ? "" : pathe[2][2] + "");

    }

    /* private Movement_ActionP2() {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt00 = new javax.swing.JLabel();
        txt01 = new javax.swing.JLabel();
        txt02 = new javax.swing.JLabel();
        txt10 = new javax.swing.JLabel();
        txt11 = new javax.swing.JLabel();
        txt12 = new javax.swing.JLabel();
        txt22 = new javax.swing.JLabel();
        txt21 = new javax.swing.JLabel();
        txt20 = new javax.swing.JLabel();
        txtBut = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txt00.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt00.setForeground(new java.awt.Color(0, 0, 0));
        txt00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt00.setText("1");
        txt00.setToolTipText("");
        txt00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt01.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt01.setForeground(new java.awt.Color(0, 0, 0));
        txt01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt01.setText("2");
        txt01.setToolTipText("");
        txt01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt02.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt02.setForeground(new java.awt.Color(0, 0, 0));
        txt02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt02.setText("3");
        txt02.setToolTipText("");
        txt02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt10.setForeground(new java.awt.Color(0, 0, 0));
        txt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt10.setText("8");
        txt10.setToolTipText("");
        txt10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt11.setForeground(new java.awt.Color(0, 0, 0));
        txt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt11.setText(" ");
        txt11.setToolTipText("");
        txt11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt12.setForeground(new java.awt.Color(0, 0, 0));
        txt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt12.setText("4");
        txt12.setToolTipText("");
        txt12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt22.setForeground(new java.awt.Color(0, 0, 0));
        txt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt22.setText("5");
        txt22.setToolTipText("");
        txt22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt21.setForeground(new java.awt.Color(0, 0, 0));
        txt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt21.setText("6");
        txt21.setToolTipText("");
        txt21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txt20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt20.setForeground(new java.awt.Color(0, 0, 0));
        txt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt20.setText("7");
        txt20.setToolTipText("");
        txt20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        txtBut.setBackground(new java.awt.Color(255, 255, 255));
        txtBut.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtBut.setForeground(new java.awt.Color(0, 0, 0));
        txtBut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBut.setText("C'est le but");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle8/Windows_Close_Program_22531 (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle8/icons8-next-page-48 -.png"))); // NOI18N
        jButton8.setToolTipText("l'état suivant");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(txtBut, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int getRowBlanc(int[][] node) {
        int str = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (node[i][j] == 0) {
                    str = i;
                    break;
                }

            }

        }
        return str;
    }

    public int getColBlanc(int[][] node) {
        int str = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (node[i][j] == 0) {
                    str = j;
                    break;
                }

            }

        }
        return str;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        i=0;
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        txtBut.setText("");
        if (i < path.length()) {
            if (path.charAt(i) == 'U') {
                int row = getRowBlanc(pathe);
                int col = getColBlanc(pathe);
                System.out.println("row =" + row + "col=" + col);
                int tmp = 0;
                if (row > 0) {
                    tmp = pathe[row][col];
                    pathe[row][col] = pathe[row - 1][col];
                    pathe[row - 1][col] = tmp;
                    for (int i = 0; i < 3; i++) {
                        for (int j = 0; j < 3; j++) {
                            System.out.print(pathe[i][j] + " ");
                        }
                        System.out.println();
                    }
                    txt00.setText(pathe[0][0] == 0 ? "" : pathe[0][0] + "");
                    txt01.setText(pathe[0][1] == 0 ? "" : pathe[0][1] + "");
                    txt02.setText(pathe[0][2] == 0 ? "" : pathe[0][2] + "");
                    txt10.setText(pathe[1][0] == 0 ? "" : pathe[1][0] + "");
                    txt11.setText(pathe[1][1] == 0 ? "" : pathe[1][1] + "");
                    txt12.setText(pathe[1][2] == 0 ? "" : pathe[1][2] + "");
                    txt20.setText(pathe[2][0] == 0 ? "" : pathe[2][0] + "");
                    txt21.setText(pathe[2][1] == 0 ? "" : pathe[2][1] + "");
                    txt22.setText(pathe[2][2] == 0 ? "" : pathe[2][2] + "");
                } else {
                    JOptionPane.showMessageDialog(this, "Veuillez reessayer autre Movement.", "Movement impossible", JOptionPane.ERROR_MESSAGE);

                }
            }
            if (path.charAt(i) == 'L') {
                int row = getRowBlanc(pathe);
                int col = getColBlanc(pathe);
                int tmp = 0;
                if (col > 0) {
                    tmp = pathe[row][col];
                    pathe[row][col] = pathe[row][col - 1];
                    pathe[row][col - 1] = tmp;
                    for (int i = 0; i < 3; i++) {
                        for (int j = 0; j < 3; j++) {
                            System.out.print(pathe[i][j] + " ");
                        }
                        System.out.println();
                    }
                    txt00.setText(pathe[0][0] == 0 ? "" : pathe[0][0] + "");
                    txt01.setText(pathe[0][1] == 0 ? "" : pathe[0][1] + "");
                    txt02.setText(pathe[0][2] == 0 ? "" : pathe[0][2] + "");
                    txt10.setText(pathe[1][0] == 0 ? "" : pathe[1][0] + "");
                    txt11.setText(pathe[1][1] == 0 ? "" : pathe[1][1] + "");
                    txt12.setText(pathe[1][2] == 0 ? "" : pathe[1][2] + "");
                    txt20.setText(pathe[2][0] == 0 ? "" : pathe[2][0] + "");
                    txt21.setText(pathe[2][1] == 0 ? "" : pathe[2][1] + "");
                    txt22.setText(pathe[2][2] == 0 ? "" : pathe[2][2] + "");
                } else {
                    JOptionPane.showMessageDialog(this, "Veuillez reessayer autre Movement.", "Movement impossible", JOptionPane.ERROR_MESSAGE);

                }
            }
            if (path.charAt(i) == 'D') {
                int row = getRowBlanc(pathe);
                int col = getColBlanc(pathe);
                System.out.println("row =" + row + "col=" + col);
                int tmp = 0;
                if (row < 2) {
                    tmp = pathe[row][col];
                    pathe[row][col] = pathe[row + 1][col];
                    pathe[row + 1][col] = tmp;
                    for (int i = 0; i < 3; i++) {
                        for (int j = 0; j < 3; j++) {
                            System.out.print(pathe[i][j] + " ");
                        }
                        System.out.println();
                    }
                    txt00.setText(pathe[0][0] == 0 ? "" : pathe[0][0] + "");
                    txt01.setText(pathe[0][1] == 0 ? "" : pathe[0][1] + "");
                    txt02.setText(pathe[0][2] == 0 ? "" : pathe[0][2] + "");
                    txt10.setText(pathe[1][0] == 0 ? "" : pathe[1][0] + "");
                    txt11.setText(pathe[1][1] == 0 ? "" : pathe[1][1] + "");
                    txt12.setText(pathe[1][2] == 0 ? "" : pathe[1][2] + "");
                    txt20.setText(pathe[2][0] == 0 ? "" : pathe[2][0] + "");
                    txt21.setText(pathe[2][1] == 0 ? "" : pathe[2][1] + "");
                    txt22.setText(pathe[2][2] == 0 ? "" : pathe[2][2] + "");
                } else {
                    JOptionPane.showMessageDialog(this, "Veuillez reessayer autre Movement.", "Movement impossible", JOptionPane.ERROR_MESSAGE);

                }
            }
            if (path.charAt(i) == 'R') {
                int row = getRowBlanc(pathe);
                int col = getColBlanc(pathe);
                System.out.println("row =" + row + "col=" + col);
                int tmp = 0;

                if (col < 2) {
                    tmp = pathe[row][col];
                    pathe[row][col] = pathe[row][col + 1];
                    pathe[row][col + 1] = tmp;
                    for (int i = 0; i < 3; i++) {
                        for (int j = 0; j < 3; j++) {
                            System.out.print(pathe[i][j] + " ");
                        }
                        System.out.println();
                    }
                    txt00.setText(pathe[0][0] == 0 ? "" : pathe[0][0] + "");
                    txt01.setText(pathe[0][1] == 0 ? "" : pathe[0][1] + "");
                    txt02.setText(pathe[0][2] == 0 ? "" : pathe[0][2] + "");
                    txt10.setText(pathe[1][0] == 0 ? "" : pathe[1][0] + "");
                    txt11.setText(pathe[1][1] == 0 ? "" : pathe[1][1] + "");
                    txt12.setText(pathe[1][2] == 0 ? "" : pathe[1][2] + "");
                    txt20.setText(pathe[2][0] == 0 ? "" : pathe[2][0] + "");
                    txt21.setText(pathe[2][1] == 0 ? "" : pathe[2][1] + "");
                    txt22.setText(pathe[2][2] == 0 ? "" : pathe[2][2] + "");
                } else {
                    JOptionPane.showMessageDialog(this, "Veuillez reessayer autre Movement.", "Movement impossible", JOptionPane.ERROR_MESSAGE);

                }

            }
            i++;
            

        } else {
            txtBut.setText("C'est le but !!");
            jButton8.setEnabled(false);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt00;
    private javax.swing.JLabel txt01;
    private javax.swing.JLabel txt02;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt20;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    private javax.swing.JLabel txtBut;
    // End of variables declaration//GEN-END:variables
}
