/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Partie2;

import Partie2.Algorithme.PSO;
import Partie2.Algorithme.Particle;
import src.Puzzle;
import static Partie2.GeneticAlgoForm.Cnf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import puzzle8.Configuration;
import puzzle8.TaquinNode;
import puzzle8.Welcom_Form;

/**
 *
 * @author ABEDSSAMED
 */
public class PSOALGOFORM extends javax.swing.JFrame {

    /**
     * Creates new form GAFORM
     */
    public PSOALGOFORM() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        size.setModel(new SpinnerNumberModel(new Integer(100), new Integer(1), null, new Integer(1)));
        iterations.setModel(new SpinnerNumberModel(new Integer(1000), new Integer(0), null, new Integer(1)));
        param1.setModel(new SpinnerNumberModel(new Float(0.5), new Float(0), null, new Float(0.1)));
        param2.setModel(new SpinnerNumberModel(new Float(0.5), new Float(0), null, new Float(0.1)));
        param3.setModel(new SpinnerNumberModel(new Float(0.5), new Float(0), null, new Float(0.1)));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        size = new javax.swing.JSpinner();
        param1 = new javax.swing.JSpinner();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        param2 = new javax.swing.JSpinner();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSolution = new javax.swing.JTextArea();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        btnResoudre4 = new javax.swing.JButton();
        btnSolv4 = new javax.swing.JButton();
        iterations = new javax.swing.JSpinner();
        jLabel60 = new javax.swing.JLabel();
        param3 = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        txtSolSize = new javax.swing.JLabel();
        textTime = new javax.swing.JLabel();
        txtgen = new javax.swing.JLabel();
        txtExplored = new javax.swing.JLabel();
        txt00 = new javax.swing.JTextField();
        txt02 = new javax.swing.JTextField();
        txt01 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        cbxman = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Algorithme PSO");

        jLabel51.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Taille d'une essaime :");

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Nombre max de génération  :");

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Coeff cognitive C1:");

        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Coeff social C2 :");

        txtSolution.setEditable(false);
        txtSolution.setBackground(new java.awt.Color(255, 255, 255));
        txtSolution.setColumns(20);
        txtSolution.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtSolution.setForeground(new java.awt.Color(0, 0, 0));
        txtSolution.setRows(5);
        txtSolution.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204)));
        jScrollPane6.setViewportView(txtSolution);

        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Solution :");

        jLabel56.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Taille  de la Solution :");

        jLabel57.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Temps d'exécution :");

        jLabel58.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Nombre d'itération  :");

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Nombre de particule :");

        btnResoudre4.setBackground(new java.awt.Color(102, 0, 204));
        btnResoudre4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnResoudre4.setForeground(new java.awt.Color(255, 255, 255));
        btnResoudre4.setText("Résoudre");
        btnResoudre4.setToolTipText("La résolution peut prendre long temp !!");
        btnResoudre4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnResoudre4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnResoudreStateChanged(evt);
            }
        });
        btnResoudre4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResoudreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResoudreMousePressed(evt);
            }
        });
        btnResoudre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResoudreActionPerformed(evt);
            }
        });
        btnResoudre4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResoudreKeyPressed(evt);
            }
        });

        btnSolv4.setBackground(new java.awt.Color(102, 0, 204));
        btnSolv4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSolv4.setForeground(new java.awt.Color(255, 255, 255));
        btnSolv4.setText("Randomise");
        btnSolv4.setToolTipText("La résolution peut prendre long temp !!");
        btnSolv4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        btnSolv4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSolvStateChanged(evt);
            }
        });
        btnSolv4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolvMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSolvMousePressed(evt);
            }
        });
        btnSolv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolvActionPerformed(evt);
            }
        });
        btnSolv4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSolvKeyPressed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Coeff  d'iterview  :");

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puzzle8/Windows_Close_Program_22531 (1).png"))); // NOI18N
        jButton7.setToolTipText("Quitter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtSolSize.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtSolSize.setForeground(new java.awt.Color(0, 0, 0));

        textTime.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        textTime.setForeground(new java.awt.Color(0, 0, 0));

        txtgen.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtgen.setForeground(new java.awt.Color(0, 0, 0));

        txtExplored.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtExplored.setForeground(new java.awt.Color(0, 0, 0));

        txt00.setBackground(new java.awt.Color(255, 255, 255));
        txt00.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt00.setForeground(new java.awt.Color(0, 0, 0));
        txt00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt00.setText("7");
        txt00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt00.setEnabled(false);
        txt00.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt02.setBackground(new java.awt.Color(255, 255, 255));
        txt02.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt02.setForeground(new java.awt.Color(0, 0, 0));
        txt02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt02.setText("3");
        txt02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt02.setEnabled(false);
        txt02.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt01.setBackground(new java.awt.Color(255, 255, 255));
        txt01.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt01.setForeground(new java.awt.Color(0, 0, 0));
        txt01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt01.setText("1");
        txt01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt01.setEnabled(false);
        txt01.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt10.setBackground(new java.awt.Color(255, 255, 255));
        txt10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt10.setForeground(new java.awt.Color(0, 0, 0));
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("2");
        txt10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt10.setEnabled(false);
        txt10.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt11.setBackground(new java.awt.Color(255, 255, 255));
        txt11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt11.setForeground(new java.awt.Color(0, 0, 0));
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setText("6");
        txt11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt11.setEnabled(false);
        txt11.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt12.setBackground(new java.awt.Color(255, 255, 255));
        txt12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt12.setForeground(new java.awt.Color(0, 0, 0));
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setText("4");
        txt12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt12.setEnabled(false);
        txt12.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt22.setBackground(new java.awt.Color(255, 255, 255));
        txt22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt22.setForeground(new java.awt.Color(0, 0, 0));
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setText("5");
        txt22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt22.setEnabled(false);
        txt22.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt21.setBackground(new java.awt.Color(255, 255, 255));
        txt21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt21.setForeground(new java.awt.Color(0, 0, 0));
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setText("0");
        txt21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt21.setEnabled(false);
        txt21.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txt20.setBackground(new java.awt.Color(255, 255, 255));
        txt20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt20.setForeground(new java.awt.Color(0, 0, 0));
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setText("8");
        txt20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt20.setEnabled(false);
        txt20.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        cbxman.setBackground(new java.awt.Color(255, 255, 255));
        cbxman.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cbxman.setForeground(new java.awt.Color(0, 0, 0));
        cbxman.setText("Saisir manuale");
        cbxman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxman, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iterations, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSolSize, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(txtExplored, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSolv4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResoudre4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(155, 209, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtSolSize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExplored, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSolv4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResoudre4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(param3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addComponent(cbxman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel49)
                    .addContainerGap(616, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  static Configuration Cnf = new Configuration();

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Welcom_Form W = new Welcom_Form();
        W.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSolvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSolvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvKeyPressed

    private void btnSolvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolvActionPerformed
        // TODO add your handling code here:
        txtSolution.setText("");
        txtSolSize.setText("");
        textTime.setText("");
        txtExplored.setText("");
        txtgen.setText("");
        Cnf.generation("Medium");

        txt00.setText(Cnf.getMedium()[0][0] == 0 ? "" : Cnf.getMedium()[0][0] + "");
        txt01.setText(Cnf.getMedium()[0][1] == 0 ? "" : Cnf.getMedium()[0][1] + "");
        txt02.setText(Cnf.getMedium()[0][2] == 0 ? "" : Cnf.getMedium()[0][2] + "");
        txt10.setText(Cnf.getMedium()[1][0] == 0 ? "" : Cnf.getMedium()[1][0] + "");
        txt11.setText(Cnf.getMedium()[1][1] == 0 ? "" : Cnf.getMedium()[1][1] + "");
        txt12.setText(Cnf.getMedium()[1][2] == 0 ? "" : Cnf.getMedium()[1][2] + "");
        txt20.setText(Cnf.getMedium()[2][0] == 0 ? "" : Cnf.getMedium()[2][0] + "");
        txt21.setText(Cnf.getMedium()[2][1] == 0 ? "" : Cnf.getMedium()[2][1] + "");
        txt22.setText(Cnf.getMedium()[2][2] == 0 ? "" : Cnf.getMedium()[2][2] + "");
    }//GEN-LAST:event_btnSolvActionPerformed

    private void btnSolvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolvMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvMousePressed

    private void btnSolvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvMouseClicked

    private void btnSolvStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSolvStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolvStateChanged

    private void btnResoudreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResoudreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResoudreKeyPressed
    public String str(int[][] node) {
        String str = "";
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (node[i][j] == 0) {
                    str = str + "9";
                } else {
                    str = str + node[i][j];
                }
            }

        }
        return str;
    }
    static int[][] state = new int[3][3];
    private void btnResoudreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResoudreActionPerformed
        // TODO add your handling code here:
        if (cbxman.isSelected()) {
//            String stat = txt00.getText() + txt01.getText() + txt02.getText() + txt10.getText() + txt11.getText() + txt12.getText() + txt20.getText() + txt21.getText() + txt22.getText() + "";
//            String s = "";
//            for (int i = 0; i < 9; i++) {
//                if (stat.charAt(i) != ' ') {
//                    s = s + stat.charAt(i);
//                } else {
//                    s = s + "9";
//                }
//            }

            state[0][0] = Integer.parseInt(txt00.getText() == "" ? "0" : txt00.getText());
            state[0][1] = Integer.parseInt(txt01.getText() == "" ? "0" : txt01.getText());
            state[0][2] = Integer.parseInt(txt02.getText() == "" ? "0" : txt02.getText());
            state[1][0] = Integer.parseInt(txt10.getText() == "" ? "0" : txt10.getText());
            state[1][1] = Integer.parseInt(txt11.getText() == "" ? "0" : txt11.getText());
            state[1][2] = Integer.parseInt(txt12.getText() == "" ? "0" : txt12.getText());
            state[2][0] = Integer.parseInt(txt20.getText() == "" ? "0" : txt20.getText());
            state[2][1] = Integer.parseInt(txt21.getText() == "" ? "0" : txt21.getText());
            state[2][2] = Integer.parseInt(txt22.getText() == "" ? "0" : txt22.getText());

            long starttime = 0, endtime = 0;
            String solution = "";
            Particle.INITIAL_STATE = new Puzzle(Integer.parseInt(str(state)));
            PSO s3 = new PSO();
            try {
                size.commitEdit();
                iterations.commitEdit();
                param1.commitEdit();
                param2.commitEdit();
                param3.commitEdit();
            } catch (java.text.ParseException e) {
            }
            s3.c1 = (Float) param1.getValue();
            s3.c2 = (Float) param2.getValue();
            s3.w = (Float) param3.getValue();
            s3.MAX_SWARM_SIZE = (Integer) size.getValue();
            starttime = System.currentTimeMillis();
            s3.initSwarm();
            solution = s3.runPSO((Integer) iterations.getValue());
            endtime = System.currentTimeMillis();
            if (solution.contentEquals("X")) {
                JOptionPane.showMessageDialog(this, "Veuillez reessayer avec d'autres paramètres.", "Solution non trouvée", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtExplored.setText(s3.nb_iteration + "");
            txtgen.setText(s3.swarm_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");
            Movement_ActionP2 P = new Movement_ActionP2(solution, state);
            P.show();

        } else {

            

            long starttime = 0, endtime = 0;
            String solution = "";
            Particle.INITIAL_STATE = new Puzzle(Integer.parseInt(str(Cnf.getMedium())));
            PSO s3 = new PSO();
            try {
                size.commitEdit();
                iterations.commitEdit();
                param1.commitEdit();
                param2.commitEdit();
                param3.commitEdit();
            } catch (java.text.ParseException e) {
            }
            s3.c1 = (Float) param1.getValue();
            s3.c2 = (Float) param2.getValue();
            s3.w = (Float) param3.getValue();
            s3.MAX_SWARM_SIZE = (Integer) size.getValue();
            starttime = System.currentTimeMillis();
            s3.initSwarm();
            solution = s3.runPSO((Integer) iterations.getValue());
            endtime = System.currentTimeMillis();
            if (solution.contentEquals("X")) {
                JOptionPane.showMessageDialog(this, "Veuillez reessayer avec d'autres paramètres.", "Solution non trouvée", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtExplored.setText(s3.nb_iteration + "");
            txtgen.setText(s3.swarm_size + "");
            txtSolution.setText(solution);
            txtSolSize.setText("" + solution.length());
            textTime.setText(endtime - starttime + "ms");
            Movement_ActionP2 P = new Movement_ActionP2(solution,Cnf.getMedium());
            P.show();
        }

    }//GEN-LAST:event_btnResoudreActionPerformed

    private void btnResoudreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResoudreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResoudreMousePressed

    private void btnResoudreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResoudreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResoudreMouseClicked

    private void btnResoudreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnResoudreStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResoudreStateChanged

    private void cbxmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmanActionPerformed
        // TODO add your handling code here:
        if (cbxman.isSelected()) {
            btnSolv4.setVisible(false);
            txt00.enable(true);
            txt01.enable(true);
            txt02.enable(true);
            txt10.enable(true);
            txt11.enable(true);
            txt12.enable(true);
            txt20.enable(true);
            txt21.enable(true);
            txt22.enable(true);

        } else {
            btnSolv4.setVisible(true);
            txt00.enable(false);
            txt01.enable(false);
            txt02.enable(false);
            txt10.enable(false);
            txt11.enable(false);
            txt12.enable(false);
            txt20.enable(false);
            txt21.enable(false);
            txt22.enable(false);
        }
    }//GEN-LAST:event_cbxmanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSOALGOFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSOALGOFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSOALGOFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSOALGOFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PSOALGOFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResoudre4;
    private javax.swing.JButton btnSolv4;
    private javax.swing.JCheckBox cbxman;
    private javax.swing.JSpinner iterations;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner param1;
    private javax.swing.JSpinner param2;
    private javax.swing.JSpinner param3;
    private javax.swing.JSpinner size;
    private javax.swing.JLabel textTime;
    private javax.swing.JTextField txt00;
    private javax.swing.JTextField txt01;
    private javax.swing.JTextField txt02;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JLabel txtExplored;
    private javax.swing.JLabel txtSolSize;
    private javax.swing.JTextArea txtSolution;
    private javax.swing.JLabel txtgen;
    // End of variables declaration//GEN-END:variables
}
